diamm/diamm

- diamm/templates/website/search/results/result.jinja2
- diamm/templates/website/search/results/source.jinja2
> Revert "Feat/source image"

- diamm/templates/website/search/results/result.jinja2
- diamm/templates/website/search/results/source.jinja2
Refs issue #36 
Related pull request #46 
Adds an icon to the left of source titles to indicate the source has images
> Source image indication in search

- diamm/serializers/iiif/service.py
> New: adds title and url of an item's composition to the service seriaizer

- diamm/serializers/iiif/service.py
- diamm/serializers/search/item.py
> Adds genres to service serializer

- diamm/serializers/website/source.py
- diamm/static/stylesheets/_source.scss
- diamm/static/stylesheets/styles.css
- diamm/templates/website/source/source_detail.jinja2
> New: adds archive logo to source detail view

- diamm/serializers/search/source_copyist.py
- diamm/serializers/search/source_relationship.py
- diamm/serializers/website/archive.py
- diamm/serializers/website/person.py
- diamm/templates/website/archive/archive_detail.jinja2
- diamm/templates/website/person/person_detail.jinja2
added image icons next to sources that have images in source lists that appear in archives and people.
> added image icons in archives and people

- diamm/models/data/archive_note.py
> Adds 'Other Names' to archive notes

- diamm/templates/website/city/city_detail.jinja2
- diamm/templates/website/city/city_list.jinja2
- diamm/templates/website/country/country_detail.jinja2
- diamm/templates/website/country/country_list.jinja2
> Refactor: converts templates to skeleton css

- diamm/static/javascripts/lib/iiif-structure.js
> WIP: Improves the scrolling MSS view

- .gitignore
- diamm/views/website/search.py
> Updated master branch

- diamm/management/commands/attach_folder_to_source.py
This adds the ability to delete an image in the database if it does not exist on the filesystem.
> New: Allow users to delete images

- diamm/management/commands/attach_folder_to_source.py
More logging and formatting, and some extra intelligence for the matching script.
> WIP: Logging and formatting

- diamm/management/commands/reindex_all.py
- diamm/serializers/website/composition.py
- diamm/settings.py
- diamm/static/apps/source/src/actions/iiif_actions.js
> Latest Release

- diamm/admin/site/problem_report.py
> Fixed: Problem Reports do not return 500 errors

- diamm/admin/data/archive.py
- diamm/admin/data/archive_note.py
- diamm/admin/data/genre.py
- diamm/admin/data/image.py
- diamm/admin/data/mensuration.py
- diamm/admin/data/page.py
- diamm/admin/data/source.py
- diamm/admin/data/source_note.py
- diamm/admin/data/source_provenance.py
- diamm/admin/site/problem_report.py
- diamm/models/data/archive_note.py
This release adds several improvements to the admin interface.
> Improvements in admin interface

- diamm/models/data/set.py
> Fixed: Order set shelfmarks alphabetically.

- diamm/serializers/search/bibliography.py
- diamm/serializers/website/composition.py
- diamm/templates/admin/diamm_data/source/change_form.html
> Fixed: Calls to template renderer changed in Jinja Backend

- diamm/serializers/search/item_bibliography.py
> Fixed: Templating in item bibliography

- diamm/templates/base.jinja2
- requirements.txt
Also includes a small fix for the footer.
> Normalizing versions

- diamm/templates/website/bibliography/bibliography_entry.jinja2
> Fixed: Glitches with editor entries

- diamm/serializers/website/city.py
Missing early/late dates caused retrieval to crash.
Fixes #341
> Fixed: Problem with City lookup

- diamm/admin/data/item.py
Also, filter by records already linked.
> New: Show items linked to page records

- diamm/management/commands/create_pages_and_images.py
Also added more special image types
> Fixed: Will not crash if no filename match

- diamm/templates/base.jinja2
- diamm/templates/index.jinja2
> Fixed: Prevent FOUC

- diamm/helpers/solr_helpers.py
Fixed bug with duplicate search results
Fixes #429
> Release 2019-03-16
